### ISSUE TITLE
CFScrape Error after v.1.1.3

### ISSUE THREAD

**Issue by averagejoe365** [thewhiteh4t/pwnedOrNot#15]
**Describe the bug**
Since the update to v1.1.3, pwnedOrNot.py fails to run due to missing cfscrape. 

**To Reproduce**
`root@kali:~/tools/pwnedOrNot# ./install.sh 
[!] Updating...

[!] Installing Dependencies...
    Python
    NodeJS
    Requests
    CfScrape

[!] Installed.
root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -h
Traceback (most recent call last):
  File "pwnedornot.py", line 10, in <module>
    import cfscrape
ModuleNotFoundError: No module named 'cfscrape'
root@kali:~/tools/pwnedOrNot# python pwnedornot.py -h
  File "pwnedornot.py", line 110
    print ('\n' + G + '[+]' + C + ' Checking Breach status for ' + W + '{}'.format(addr), end = '')
                                                                                              ^
SyntaxError: invalid syntax
root@kali:~/tools/pwnedOrNot# 
`

**Expected behavior**
No matter the option that is selected "-e -h -n -l, etc.", still received the missing cfscrape error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser N/A
 - Version 2018.4

**Additional context**
Old directory was removed via "rm -r". New pwnedOrNot was installed via "git clone" after Issue 14 was resolved.

**Comment by averagejoe365** [comment]
FYSA, cfscrape is installed as shown below:

```
root@kali:~/tools/pwnedOrNot# pip install cfscrape
Requirement already satisfied: cfscrape in /usr/local/lib/python2.7/dist-packages (1.9.6)
Requirement already satisfied: requests>=2.0.0 in /usr/lib/python2.7/dist-packages (from cfscrape) (2.20.0)
root@kali:~/tools/pwnedOrNot# 
```

**Comment by thewhiteh4t** [comment]
I have updated install.sh please follow this:
`cd pwnedOrNot`
`git pull`
`./install.sh`
Should work after this

**Comment by averagejoe365** [comment]
No go

```
root@kali:~/tools# cd pwnedOrNot
root@kali:~/tools/pwnedOrNot# git pull
Already up to date.
root@kali:~/tools/pwnedOrNot# ./install.sh
[!] Updating...

[!] Installing Dependencies...
    Python
    NodeJS
    Requests
    CfScrape

[!] Installed.
root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -h
Traceback (most recent call last):
  File "pwnedornot.py", line 10, in <module>
    import cfscrape
ModuleNotFoundError: No module named 'cfscrape'
root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -e [redacted]@gmail.com
Traceback (most recent call last):
  File "pwnedornot.py", line 10, in <module>
    import cfscrape
ModuleNotFoundError: No module named 'cfscrape'
root@kali:~/tools/pwnedOrNot# 
```

**Comment by thewhiteh4t** [comment]
Share install.log @averagejoe365

**Comment by averagejoe365** [comment]
```
root@kali:~/tools/pwnedOrNot# cat install.log
Hit:1 http://archive.linux.duke.edu/kalilinux/kali kali-rolling InRelease
Reading package lists...
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
./install.sh: line 10: pip3: command not found
./install.sh: line 12: pip3: command not found
root@kali:~/tools/pwnedOrNot# 

```

**Comment by thewhiteh4t** [comment]
Yeah got the error execute 
dpkg --configure -a 
And share output 
@averagejoe365

**Comment by averagejoe365** [comment]
Ran --configure -a. Re-running ./install.sh ATM

**Comment by averagejoe365** [comment]
```
root@kali:~/tools/pwnedOrNot# cat install.log
Hit:1 http://archive.linux.duke.edu/kalilinux/kali kali-rolling InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.7.2-1).
python3 set to manually installed.
The following packages were automatically installed and are no longer required:
  libdee-1.0-4 libgmime-3.0-0 libgtk2-perl libpango-perl libxapian30
  libzeitgeist-2.0-0 python-backports.ssl-match-hostname python-pam python3.6
  python3.6-minimal x11proto-dri2-dev x11proto-gl-dev zeitgeist-core
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  dh-python libpython3-dev libpython3.7 libpython3.7-dev libpython3.7-minimal
  libpython3.7-stdlib python3-dev python3-entrypoints python3-keyring
  python3-keyrings.alt python3-pkg-resources python3-secretstorage
  python3-setuptools python3-wheel python3.7 python3.7-dev python3.7-minimal
Suggested packages:
  libkf5wallet-bin gir1.2-gnomekeyring-1.0 python-secretstorage-doc
  python-setuptools-doc python3.7-venv python3.7-doc
The following NEW packages will be installed:
  dh-python libpython3-dev libpython3.7 libpython3.7-dev python3-dev
  python3-entrypoints python3-keyring python3-keyrings.alt python3-pip
  python3-secretstorage python3-setuptools python3-wheel python3.7-dev
The following packages will be upgraded:
  libpython3.7-minimal libpython3.7-stdlib python3-pkg-resources python3.7
  python3.7-minimal
5 upgraded, 13 newly installed, 0 to remove and 822 not upgraded.
Need to get 55.6 MB of archives.
After this operation, 91.8 MB of additional disk space will be used.
Get:1 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3.7 amd64 3.7.3~rc1-1 [330 kB]
Get:2 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3.7-minimal amd64 3.7.3~rc1-1 [1,731 kB]
Get:3 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 libpython3.7-stdlib amd64 3.7.3~rc1-1 [1,731 kB]
Get:4 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 libpython3.7-minimal amd64 3.7.3~rc1-1 [588 kB]
Get:5 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 dh-python all 3.20190308 [99.3 kB]
Get:6 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 libpython3.7 amd64 3.7.3~rc1-1 [1,498 kB]
Get:7 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 libpython3.7-dev amd64 3.7.3~rc1-1 [48.4 MB]
Get:8 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 libpython3-dev amd64 3.7.2-1 [20.1 kB]
Get:9 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3.7-dev amd64 3.7.3~rc1-1 [509 kB]
Get:10 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-dev amd64 3.7.2-1 [1,256 B]
Get:11 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-entrypoints all 0.3-1 [5,508 B]
Get:12 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-secretstorage all 2.3.1-2 [14.2 kB]
Get:13 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-keyring all 17.1.1-1 [43.1 kB]
Get:14 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-keyrings.alt all 3.1.1-1 [18.2 kB]
Get:15 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-pip all 18.1-4 [171 kB]
Get:16 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-pkg-resources all 40.8.0-1 [153 kB]
Get:17 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-setuptools all 40.8.0-1 [306 kB]
Get:18 http://archive.linux.duke.edu/kalilinux/kali kali-rolling/main amd64 python3-wheel all 0.32.3-2 [19.4 kB]
apt-listchanges: Reading changelogs...
Fetched 55.6 MB in 20s (2,754 kB/s)
(Reading database ... 344040 files and directories currently installed.)
Preparing to unpack .../00-python3.7_3.7.3~rc1-1_amd64.deb ...
Unpacking python3.7 (3.7.3~rc1-1) over (3.7.2-2) ...
Preparing to unpack .../01-python3.7-minimal_3.7.3~rc1-1_amd64.deb ...
Unpacking python3.7-minimal (3.7.3~rc1-1) over (3.7.2-2) ...
Preparing to unpack .../02-libpython3.7-stdlib_3.7.3~rc1-1_amd64.deb ...
Unpacking libpython3.7-stdlib:amd64 (3.7.3~rc1-1) over (3.7.2-2) ...
Preparing to unpack .../03-libpython3.7-minimal_3.7.3~rc1-1_amd64.deb ...
Unpacking libpython3.7-minimal:amd64 (3.7.3~rc1-1) over (3.7.2-2) ...
Selecting previously unselected package dh-python.
Preparing to unpack .../04-dh-python_3.20190308_all.deb ...
Unpacking dh-python (3.20190308) ...
Selecting previously unselected package libpython3.7:amd64.
Preparing to unpack .../05-libpython3.7_3.7.3~rc1-1_amd64.deb ...
Unpacking libpython3.7:amd64 (3.7.3~rc1-1) ...
Selecting previously unselected package libpython3.7-dev:amd64.
Preparing to unpack .../06-libpython3.7-dev_3.7.3~rc1-1_amd64.deb ...
Unpacking libpython3.7-dev:amd64 (3.7.3~rc1-1) ...
Selecting previously unselected package libpython3-dev:amd64.
Preparing to unpack .../07-libpython3-dev_3.7.2-1_amd64.deb ...
Unpacking libpython3-dev:amd64 (3.7.2-1) ...
Selecting previously unselected package python3.7-dev.
Preparing to unpack .../08-python3.7-dev_3.7.3~rc1-1_amd64.deb ...
Unpacking python3.7-dev (3.7.3~rc1-1) ...
Selecting previously unselected package python3-dev.
Preparing to unpack .../09-python3-dev_3.7.2-1_amd64.deb ...
Unpacking python3-dev (3.7.2-1) ...
Selecting previously unselected package python3-entrypoints.
Preparing to unpack .../10-python3-entrypoints_0.3-1_all.deb ...
Unpacking python3-entrypoints (0.3-1) ...
Selecting previously unselected package python3-secretstorage.
Preparing to unpack .../11-python3-secretstorage_2.3.1-2_all.deb ...
Unpacking python3-secretstorage (2.3.1-2) ...
Selecting previously unselected package python3-keyring.
Preparing to unpack .../12-python3-keyring_17.1.1-1_all.deb ...
Unpacking python3-keyring (17.1.1-1) ...
Selecting previously unselected package python3-keyrings.alt.
Preparing to unpack .../13-python3-keyrings.alt_3.1.1-1_all.deb ...
Unpacking python3-keyrings.alt (3.1.1-1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../14-python3-pip_18.1-4_all.deb ...
Unpacking python3-pip (18.1-4) ...
Preparing to unpack .../15-python3-pkg-resources_40.8.0-1_all.deb ...
Unpacking python3-pkg-resources (40.8.0-1) over (40.6.3-1) ...
Selecting previously unselected package python3-setuptools.
Preparing to unpack .../16-python3-setuptools_40.8.0-1_all.deb ...
Unpacking python3-setuptools (40.8.0-1) ...
Selecting previously unselected package python3-wheel.
Preparing to unpack .../17-python3-wheel_0.32.3-2_all.deb ...
Unpacking python3-wheel (0.32.3-2) ...
Setting up python3-entrypoints (0.3-1) ...
Processing triggers for mime-support (3.61) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Setting up python3-keyrings.alt (3.1.1-1) ...
Setting up python3-wheel (0.32.3-2) ...
Setting up libpython3.7-minimal:amd64 (3.7.3~rc1-1) ...
Setting up python3-pkg-resources (40.8.0-1) ...
Setting up python3.7-minimal (3.7.3~rc1-1) ...
Processing triggers for libc-bin (2.28-2) ...
Setting up python3-pip (18.1-4) ...
Processing triggers for man-db (2.8.5-1) ...




Processing triggers for gnome-menus (3.31.4-3) ...
Setting up python3-setuptools (40.8.0-1) ...
Setting up python3-secretstorage (2.3.1-2) ...
Setting up dh-python (3.20190308) ...
Setting up libpython3.7-stdlib:amd64 (3.7.3~rc1-1) ...
Setting up python3-keyring (17.1.1-1) ...
Setting up python3.7 (3.7.3~rc1-1) ...
Setting up libpython3.7:amd64 (3.7.3~rc1-1) ...
Setting up libpython3.7-dev:amd64 (3.7.3~rc1-1) ...
Setting up libpython3-dev:amd64 (3.7.2-1) ...
Setting up python3.7-dev (3.7.3~rc1-1) ...
Setting up python3-dev (3.7.2-1) ...
Processing triggers for libc-bin (2.28-2) ...
root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -h
Traceback (most recent call last):
  File "pwnedornot.py", line 10, in <module>
    import cfscrape
ModuleNotFoundError: No module named 'cfscrape'
root@kali:~/tools/pwnedOrNot# 

```

**Comment by thewhiteh4t** [comment]
Yes your pip3 is now installed properly, now again run install.sh and cfscrape should install @averagejoe365
