### ISSUE TITLE
Follow up on Issue #14

### ISSUE THREAD

**Issue by averagejoe365** [thewhiteh4t/pwnedOrNot#16]
**Describe the bug**
Hey @thewhiteh4t 

Do you have to enclose the domain within a single quotation (i.e. 'adobe.com')? Can't seem to get this to work (I know, I've been a huge pain for you so far today 😃 ). 

```
root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -d adobe.io -f '/root/Desktop/galEmails' 

	                          ______       _   __      __
    ____ _      ______  ___  ____/ / __ \_____/ | / /___  / /_
   / __ \ | /| / / __ \/ _ \/ __  / / / / ___/  |/ / __ \/ __/
  / /_/ / |/ |/ / / / /  __/ /_/ / /_/ / /  / /|  / /_/ / /_
 / .___/|__/|__/_/ /_/\___/\__,_/\____/_/  /_/ |_/\____/\__/
/_/
	
[>] Created by : thewhiteh4t
[>] Version    : 1.1.3

[+] Checking for updates...

[+] Script is up-to-date...

[+] Bypassing Cloudflare Restriction...

[-] Error : Use -e or -f with Domain Filter
root@kali:~/tools/pwnedOrNot# 
```

**Expected behavior**
Can you not combine the -f and -d operators? Must the domain be enclosed in brackets, quotes, etc.?

**Comment by averagejoe365** [comment]
```
root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -d adobe -f '/root/Desktop/galEmails' >> '/root/Desktop/adobeResults'

	                          ______       _   __      __
    ____ _      ______  ___  ____/ / __ \_____/ | / /___  / /_
   / __ \ | /| / / __ \/ _ \/ __  / / / / ___/  |/ / __ \/ __/
  / /_/ / |/ |/ / / / /  __/ /_/ / /_/ / /  / /|  / /_/ / /_
 / .___/|__/|__/_/ /_/\___/\__,_/\____/_/  /_/ |_/\____/\__/
/_/
	
[>] Created by : thewhiteh4t
[>] Version    : 1.1.5

[+] Checking for updates...

[+] Script is up-to-date...

[+] Bypassing Cloudflare Restriction...
ERROR:root:'https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "pwnedornot.py", line 282, in <module>
    main()
  File "pwnedornot.py", line 69, in main
    cookies, user_agent = cfscrape.get_tokens('https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com', user_agent='pwnedornot')
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 182, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com
root@kali:~/tools/pwnedOrNot# 
```

**Comment by averagejoe365** [comment]
It did work initially when just running one email, but once I threw in the file to run against, I started getting this response. I tried running without outputting results to a file, and then again with just a single user with the same end result errors.

**Comment by averagejoe365** [comment]
Even attempting to run with -f option without -d is now failing
```

root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -f '/root/Desktop/galEmails'

__,_/\____/_/  /_/ |_/\____/\__/
/_/
	
[>] Created by : thewhiteh4t
[>] Version    : 1.1.5

[+] Checking for updates...

[+] Script is up-to-date...

[+] Bypassing Cloudflare Restriction...

[+] Reading Emails Addresses from /root/Desktop/galEmails

[+] Checking Breach status for nuix.com_3639303235373431353631@resource.calendar.google.com [ pwned ]
Traceback (most recent call last):
  File "pwnedornot.py", line 282, in <module>
    main()
  File "pwnedornot.py", line 87, in main
    check()
  File "pwnedornot.py", line 116, in check
    simple1 = json.loads(json1)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
root@kali:~/tools/pwnedOrNot# 
```

**Comment by brunoppass** [comment]
ive the same problem

**Comment by averagejoe365** [comment]
Update:

1 - Removed "pwnedOrNot" directory using rm -r.
2 - Ran the following: apt-get update, apt-get upgrade, and apt-get dist-upgrade
3 - Ran git clone for re-installation.

Everything seemed to be working fine for a few minutes. I was able to run single checks against domains using the -d & -e options.

Example
`root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -d adobe.com -e example@gmail.com`

I then proceeded to run a file through the tool to check on a recent breach notification we received from Have I Been Pwned. 

`root@kali:~/tools/pwnedOrNot# python3 pwnedornot.py -d adobe.com -f '/root/Desktop/galEmails'` 


Everything went smoothly until about 15 or so checks in.

 ```
  / __ \ | /| / / __ \/ _ \/ __  / / / / ___/  |/ / __ \/ __/
  / /_/ / |/ |/ / / / /  __/ /_/ / /_/ / /  / /|  / /_/ / /_
 / .___/|__/|__/_/ /_/\___/\__,_/\____/_/  /_/ |_/\____/\__/
/_/
	
[>] Created by : thewhiteh4t
[>] Version    : 1.1.5

[+] Checking for updates...

[+] Script is up-to-date...

[+] Bypassing Cloudflare Restriction...
ERROR:root:'https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "pwnedornot.py", line 282, in <module>
    main()
  File "pwnedornot.py", line 69, in main
    cookies, user_agent = cfscrape.get_tokens('https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com', user_agent='pwnedornot')
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 182, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com
root@kali:~/tools/pwnedOrNot#
``` 
It seems the tools is exceeding Troy Hunt's rate limitor (i.e. too many requests within a certain time).

**Comment by averagejoe365** [comment]
FYI
https://haveibeenpwned.com/API/v2

![image](https://user-images.githubusercontent.com/39955238/55500806-0636c500-5617-11e9-9ba1-028643a92084.png)

**Comment by averagejoe365** [comment]
![image](https://user-images.githubusercontent.com/39955238/55501371-43e81d80-5618-11e9-90fa-cbe6f3597f13.png)

**Comment by thewhiteh4t** [comment]
yes it takes too long to collect dumps, so implemented threading and forgot about rate limit, i did not get any errors while initial testing, i am adding a delay of 1.6 seconds between every request, but for the Cannot Get Tokens Error, i cant do much in that case, if you repeatedly encounter token error you can try to manually visit haveibeenpwned website that should solve cloudflare problem, i will update soon

**Comment by thewhiteh4t** [comment]
@averagejoe365 updated please try now

**Comment by shisen404** [comment]
Got the following user-agent 403 error while running:
```
ERROR:root:'https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "pwnedornot.py", line 273, in <module>
    main()
  File "pwnedornot.py", line 64, in main
    cookies, user_agent = cfscrape.get_tokens('https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com', user_agent='pwnedornot')
  File "/usr/lib/python3.7/site-packages/cfscrape/__init__.py", line 182, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com
```
I have tried changing the username to different browsers, but it didn't work.

**Comment by thewhiteh4t** [comment]
@shisen404 if you read api documentation useragent needs to be anything other than our usual browser useragents so it won't work, if you simply open `https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com` in any browser you will get a 403, now as per api instructions i am using tool name as useragent, now i have answered this particular question many times (take a look in closed issues), i can't do much about this, directly contact Troy Hunt via Email and talk to him about this.

**Comment by ondrej23** [comment]
It seems to not work with any user-agent.

**Comment by thewhiteh4t** [comment]
@ondrej23 contact Troy Hunt

**Comment by ondrej23** [comment]
@thewhiteh4t Thank you for the advice!

**Comment by averagejoe365** [comment]
@thewhiteh4t My apologies on the delayed response! 

I updated to the latest version of pwnedOrNot and was able to utilize the new -b and -f operators in tandem for a few minutes, then started receiving this error again...

`
	                          ______       _   __      __
    ____ _      ______  ___  ____/ / __ \_____/ | / /___  / /_
   / __ \ | /| / / __ \/ _ \/ __  / / / / ___/  |/ / __ \/ __/
  / /_/ / |/ |/ / / / /  __/ /_/ / /_/ / /  / /|  / /_/ / /_
 / .___/|__/|__/_/ /_/\___/\__,_/\____/_/  /_/ |_/\____/\__/
/_/
	
[>] Created by : thewhiteh4t
[>] Version    : 1.1.7

[+] Checking for updates...

[+] Script is up-to-date...

[+] Bypassing Cloudflare Restriction...
ERROR:root:'https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "pwnedornot.py", line 273, in <module>
    main()
  File "pwnedornot.py", line 64, in main
    cookies, user_agent = cfscrape.get_tokens('https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com', user_agent='pwnedornot')
  File "/usr/local/lib/python3.7/dist-packages/cfscrape/__init__.py", line 182, in get_tokens
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com
root@kali:~/tools/pwnedOrNot# 
`

I tried visiting the HIBP site as you suggested in a previous post to try and mitigate this issue, but it still returns the same error.

**Comment by averagejoe365** [comment]
FYI @thewhiteh4t 
I believe this error may be appearing due to the Useragent string not being identifyied correctly.

See below for reference from HIBP on the error I continually received. 
    Ray ID: 4c97b07d5a82cf0a
    Timestamp: 2019-04-18 15:32:05 UTC
    Your IP address: 8.8.8.8
    Requested URL: haveibeenpwned.com/api/v2/breachedaccount/test@example.com
    Error reference number: 1020
    Server ID: FL_16F240
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by averagejoe365** [comment]
> 
> 
> @shisen404 if you read api documentation useragent needs to be anything other than our usual browser useragents so it won't work, if you simply open `https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com` in any browser you will get a 403, now as per api instructions i am using tool name as useragent, now i have answered this particular question many times (take a look in closed issues), i can't do much about this, directly contact Troy Hunt via Email and talk to him about this.

FYI @thewhiteh4t 
I believe this error may be appearing due to the Useragent string not being identified correctly.

See below for reference from HIBP on the error I continually received. 
```
    Ray ID: 4c97b07d5a82cf0a
    Timestamp: 2019-04-18 15:32:05 UTC
    Your IP address: 8.8.8.8
    Requested URL: haveibeenpwned.com/api/v2/breachedaccount/test@example.com
    Error reference number: 1020
    Server ID: FL_16F240
```

**Comment by averagejoe365** [comment]
Just an additional nugget of information

> ot about rate limit, i did not get any errors while initial testing, i am adding a delay of 1.6 seconds bet

When I am able to get pwnedOrNot to function, it is still erroring out with a 429 error indicating the rate limit is being triggered.

Would it be possible to double to rate limit to ~3 seconds?

**Comment by thewhiteh4t** [comment]
> > @shisen404 if you read api documentation useragent needs to be anything other than our usual browser useragents so it won't work, if you simply open `https://haveibeenpwned.com/api/v2/breachedaccount/test@example.com` in any browser you will get a 403, now as per api instructions i am using tool name as useragent, now i have answered this particular question many times (take a look in closed issues), i can't do much about this, directly contact Troy Hunt via Email and talk to him about this.
> 
> FYI @thewhiteh4t
> If the useragent is being set as ",...pwnedOrNot...", why are we receiving this when we browse to the error?
> 
> See below for reference from HIBP on the error I continually received.
> 
> ```
>     Ray ID: 4c97b07d5a82cf0a
>     Timestamp: 2019-04-18 15:32:05 UTC
>     Your IP address: 8.8.8.8
>     Requested URL: haveibeenpwned.com/api/v2/breachedaccount/test@example.com
>     Error reference number: 1020
>     Server ID: FL_16F240
>     User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> ```

when you visit from any browser take a look at the User-Agent, this is a default firefox user agent and according to haveibeenpwned it will be blocked by default,

![Screenshot from 2019-04-19 11-02-31](https://user-images.githubusercontent.com/36354846/56408589-db917100-6292-11e9-98f6-2b0991392566.png)

so as per the instructions i am using tool name, now even after this if we get 403, i was able to reproduce this by using it with tor, otherwise i never get 403, if you are not using tor and you are still getting 403 that means maybe your ip is flagged and you will have to contact Troy Hunt

**Comment by thewhiteh4t** [comment]
> Just an additional nugget of information
> 
> > ot about rate limit, i did not get any errors while initial testing, i am adding a delay of 1.6 seconds bet
> 
> When I am able to get pwnedOrNot to function, it is still erroring out with a 429 error indicating the rate limit is being triggered.
> 
> Would it be possible to double to rate limit to ~3 seconds?

@averagejoe365 i can increase it but issue is something else, i am looking into it, you are getting 429 on a request which is passed only once when tool is executed, if the request is not sent repeatedly it should not happen but its happening for some reason

**Comment by thewhiteh4t** [comment]
@averagejoe365 waiting for your response...

**Comment by thewhiteh4t** [comment]
closing due to inactivity.
