### ISSUE TITLE
FileNotFoundError: 

### ISSUE THREAD

**Issue by tfmarques23** [thewhiteh4t/pwnedOrNot#56]
[>] Created by : thewhiteh4t
[>] Version    : 1.3.0

Traceback (most recent call last):
  File "/opt/pwnedOrNot/pwnedornot.py", line 328, in <module>
    main()
  File "/opt/pwnedOrNot/pwnedornot.py", line 95, in main
    api_key()
  File "/opt/pwnedOrNot/pwnedornot.py", line 72, in api_key
    with open(conf_path, 'r') as config:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin1/.config/pwnedornot/config.json'
admin1@ubuntu:/opt/pwnedOrNot$

**Comment by dragonspace9** [comment]
wich is the problem solution? @tfmarques23
