### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by dragonspace9** [thewhiteh4t/pwnedOrNot#70]
Traceback (most recent call last):
  File "/home/dragonspace/Downloads/./pwnedornot.py", line 413, in <module>
    main()
  File "/home/dragonspace/Downloads/./pwnedornot.py", line 114, in main
    read_config()
  File "/home/dragonspace/Downloads/./pwnedornot.py", line 91, in read_config
    with open(conf_path, 'r') as config:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dragonspace/.config/pwnedornot/config.json'

I don´t know what happen, plz help @thewhiteh4t

**Comment by latestproblem** [comment]
How did you solve dragonspace 9
